### ISSUE TITLE
New sound Snippet

### ISSUE THREAD

**Issue by Jacob-Burrill** [WhitmanCS370/alt-f4#18] opened 2024-02-27 22:16 UTC
Create a new sound from a snippet of an already existing sound. We will need to find a library that is capable of breaking down sounds. This issue will be related to the saving file issue.

**Comment by Jacob-Burrill** [comment] 2024-03-05 23:18
Wednesday after we get back 3-27

**Comment by samuelboerner** [comment] 2024-04-16 22:24
dupe of #22

**Closed as not planned by samuelboerner** 2024-04-16 22:24 UTC
Labels: enhancement, Epoch 2, editing
